Inputs:
    - pt
    - eta    
    - phi    
    - photon_ID
    - electron_ID
    - muon_ID
    - neutral_hadron_ID
    - charged_hadron_ID
    - jet_index # required

Labels:
    - tau_pt
    - tau_eta
    - tau_phi
    - jet_index # required

KerasModel: onelayer_model
KerasLoss: mse
Regression: True

NormalizeInputs: 1
InputType: dense
MaxParticles: 10
Shuffle: 0
L1Reg: 0

Filename: onelayer_norm
