Inputs:
    - pt         # required
    - eta        # required
    - phi        # required
    - et
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_eta    # required
    - jet_phi    # required
    - jet_index  # required

Labels:
    - classification
    - jet_index  # required

KerasModel: conv2d_model
KerasLoss: binary_crossentropy
Regression: False

NormalizeInputs: 0
InputType: image
Shuffle: 1  
L1Reg: 0.01

BinsX: 10
MinX: -0.25
MaxX: 0.25
BinsY: 10
MinY: -0.25
MaxY: 0.25

Filename: conv2D_base
