Inputs:
    - pt    
    - eta    
    - phi    
    - et
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_index # required

Labels:
    - classification
    - jet_index # required

KerasModel: conv1d_model
KerasLoss: binary_crossentropy
Regression: False

NormalizeInputs: 1
InputType: sequence
MaxParticles: 10
Shuffle: 1
L1Reg: 0.01

Filename: conv1D_norm_base 
