Inputs:
    - pt     
    - eta    
    - phi    
    - photon_ID
    - electron_ID
    - muon_ID
    - neutral_hadron_ID
    - charged_hadron_ID
    - jet_index # required

Labels:
    - classification
    - jet_index # required

KerasModel: lstm_model_small
KerasLoss: binary_crossentropy
Regression: False

NormalizeInputs: 1 
InputType: sequence
MaxParticles: 5
Shuffle: 0
L1Reg: 0.001

Filename: lstm_norm_small
