Inputs:
    - pt     
    - eta    
    - phi    
    - energy
    - charge
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_pt # required

Labels:
    - classification
    - jet_pt # required

KerasModel: threelayer_model
KerasLoss: binary_crossentropy

NormalizeInputs: 1
InputType: dense
MaxParticles: 10
Shuffle: 1

Filename: threelayer_norm_base
