Inputs:
    - pt     
    - eta    
    - phi    
    - et
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_index # required

Labels:
    - classification
    - jet_index # required

KerasModel: lstm_model
KerasLoss: binary_crossentropy
Regression: False

NormalizeInputs: 0
InputType: sequence
MaxParticles: 10
Shuffle: 1
L1Reg: 0.01

Filename: lstm_base
