Inputs:
    - pt     
    - eta    
    - phi 
    - energy
    - charge
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_index # required

Labels:
    - classification
    - jet_index # required

KerasModel: twolayer_model
KerasLoss: binary_crossentropy

NormalizeInputs: 1
InputType: dense
MaxParticles: 10
Shuffle: 1
L1Reg: 0.01

Filename: twolayer_norm_base
