Inputs:
    - pt     
    - eta    
    - phi    
    - energy
    - photon_ID
    - lepton_ID
    - neutral_hadron_ID
    - charged_hadron_ID
    - jet_index # required

Labels:
    - classification
    - jet_index # required

KerasModel: threelayer_model
KerasLoss: binary_crossentropy
Regression: False

NormalizeInputs: 0
InputType: dense
MaxParticles: 10
Shuffle: 1
L1Reg: 0.01

Filename: threelayer_base
