Inputs:
    - pt     
    - eta   
    - phi    
    - energy
    - charge
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_pt # required

Labels:
    - classification
    - jet_pt # required

KerasModel: gru_model
KerasLoss: binary_crossentropy

NormalizeInputs: 0
InputType: sequence
MaxParticles: 10
Shuffle: 1

Filename: gru_base
