Inputs:
    - pt     
    - eta    
    - phi 
    - energy
    - charge
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_pt # required

Labels:
    - classification
    - jet_pt # required

KerasModel: twolayer_model
KerasLoss: binary_crossentropy

NormalizeInputs: 0
InputType: dense
MaxParticles: 10
Shuffle: 1

Filename: twolayer_base
