Inputs:
    - pt     
    - eta    
    - phi 
    - photon_ID
    - electron_ID
    - muon_ID
    - neutral_hadron_ID
    - charged_hadron_ID
    - jet_index # required

Labels:
    - classification
    - jet_index # required

KerasModel: twolayer_model
KerasLoss: binary_crossentropy
Regression: False

NormalizeInputs: 1
InputType: dense
MaxParticles: 10
Shuffle: 0
L1Reg: 0

Filename: twolayer_norm
