Inputs:
    - pt     
    - eta    
    - phi    
    - et
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_pt
    - jet_eta
    - jet_phi
    - jet_et
    - jet_index # required

Labels:
    - tau_pt
      #- tau_eta
      #- tau_phi
      #- tau_energy
    - jet_index # required

KerasModel: regression_model
KerasLoss: 'mse'
Regression: True

NormalizeInputs: 0
InputType: dense
MaxParticles: 10
Shuffle: 1
L1Reg: 0.01

Filename: regression_test
