Inputs:
    - pt      # required
    - eta     # required
    - phi     # required
    - energy
    - charge
    - photon_ID
    - electron_ID
    - hadron_ID
    - jet_pt  # required
    - jet_eta # required
    - jet_phi # required

Labels:
    - classification
    - jet_pt  # required

KerasModel: conv2d_model
KerasLoss: binary_crossentropy

NormalizeInputs: 0
InputType: image

BinsX: 10
MinX: -0.25
MaxX: 0.25
BinsY: 10
MinY: -0.25
MaxY: 0.25
